# Generated by Django 4.2.9 on 2024-04-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_dadosmedicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmedicos',
            old_name='especialidades',
            new_name='especialidade',
        ),
    ]
